// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHe648ha_kY3EoZfSU5qqQzoZITq1Bvqo',
    appId: '1:567615049701:web:94ba7c12a05442ff60290c',
    messagingSenderId: '567615049701',
    projectId: 'flutter-chat-a0e11',
    authDomain: 'flutter-chat-a0e11.firebaseapp.com',
    storageBucket: 'flutter-chat-a0e11.appspot.com',
    measurementId: 'G-ZLNW1X2GSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSBgwBd-1vwfJ1KDCGAbY0IWpnmfcv0rA',
    appId: '1:567615049701:android:f463e2bc1adc9db360290c',
    messagingSenderId: '567615049701',
    projectId: 'flutter-chat-a0e11',
    storageBucket: 'flutter-chat-a0e11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqwakgRI2BTlUd6cogw05C2jbkq6ugaA',
    appId: '1:567615049701:ios:ee30e767928cce6160290c',
    messagingSenderId: '567615049701',
    projectId: 'flutter-chat-a0e11',
    storageBucket: 'flutter-chat-a0e11.appspot.com',
    androidClientId: '567615049701-9om2if3cu60hlql0vh487ahmradd7t4t.apps.googleusercontent.com',
    iosClientId: '567615049701-tih1r86pbf8qhgtvc0hf8nsv4728domj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlqwakgRI2BTlUd6cogw05C2jbkq6ugaA',
    appId: '1:567615049701:ios:ab305a812f306d8e60290c',
    messagingSenderId: '567615049701',
    projectId: 'flutter-chat-a0e11',
    storageBucket: 'flutter-chat-a0e11.appspot.com',
    androidClientId: '567615049701-9om2if3cu60hlql0vh487ahmradd7t4t.apps.googleusercontent.com',
    iosClientId: '567615049701-36rupn49i13dnvb6u0vp972i3v8tburv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
